Update ci.yml

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -29,16 +29,6 @@ jobs:
     - name: Build and Capture Logs for WebApiServer
       run: dotnet build --no-incremental -warnaserror WebApiServer/WebApiServer.csproj > webapi_build.log 2>&1 || true
 
-    - name: Find npm_build.log
-      run: |
-        echo "Looking for npm_build.log..."
-        find . -name npm_build.log -exec echo "Found: {}" \;
-
-    - name: Read Content of webapi_build.log
-      run: |
-        echo "Content of webapi_build.log:"
-        cat ./webapi_build.log
-
     - name: Annotate WebApiServer Build Logs
       run: |
         # .NET build logs
@@ -49,19 +39,35 @@ jobs:
         grep "error" ./webapi_build.log | while read -r line; do
           echo "::error title=.NET Lint::$line"
         done || true
-        
-    - name: Annotate WebApiServer Build Logs
-      run: |
-        # NPM build logs
-        if [ -f WebApiServer/clientapp/npm_build.log ]; then
-          grep -i "warning" ../clientapp/npm_build.log | while read -r line; do
-            echo "::warning title=React Build::$line"
-          done || true
 
-          grep -i "error" ../clientapp/npm_build.log | while read -r line; do
-            echo "::error title=React Build::$line"
-          done || true
-        fi
+  
+    - name: Install dependencies for React
+      run: npm install
+      working-directory: ./clientapp
+
+    - name: Build npm package and capture logs
+      id: npm-build
+      run: |
+        echo "Starting npm build..."
+        npm run build > npm_build.log 2>&1 || true
+      working-directory: ./clientapp
+      continue-on-error: true
+
+    - name: Find npm_build.log
+      run: |
+        echo "Looking for npm_build.log..."
+        find . -name npm_build.log -exec echo "Found: {}" \;
+        
+    - name: Annotate npm Build Logs
+      run: |
+        # npm build warnings
+        grep -i "warning" clientapp/npm_build.log | while read -r line; do
+          echo "::warning file=${{ github.workspace }}/clientapp/npm_build.log::$line"
+        done || true
+        # npm build errors
+        grep -i "error" clientapp/npm_build.log | while read -r line; do
+          echo "::error file=${{ github.workspace }}/clientapp/npm_build.log::$line"
+        done || true
 
     - name: Test the project and capture logs
       run: dotnet test -c Release --verbosity normal WebApiServer/WebApiServer.csproj > test.log 2>&1 || true
