Update ci.yml

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -105,17 +105,27 @@ jobs:
 
     - name: Test the project and generate Cobertura report
       run: |
-        dotnet test -c Release --verbosity normal WebApiServer/WebApiServer.csproj --logger "trx;LogFileName=test-results.trx" /p:CollectCoverage=true /p:CoverletOutput=./coverage/ /p:CoverletOutputFormat=cobertura
+        mkdir -p WebApiServer
+        dotnet coverage collect dotnet test -c Release --verbosity normal --filter "Category!=Performance" WebApiServer/WebApiServer.csproj --logger "trx;LogFileName=test-results.trx" --output WebApiServer/coverage.cobertura.xml --output-format cobertura
+
+    - name: Verify Cobertura Report Generation
+      run: |
+        if [ -f "WebApiServer/coverage.cobertura.xml" ]; then
+          echo "Cobertura report generated successfully."
+        else
+          echo "Cobertura report not found!" >&2
+          exit 1
+        fi
 
     - name: Generate Coverage Report
       run: |
-        reportgenerator -reports:./coverage/coverage.cobertura.xml -targetdir:./coverage-report -reporttypes:Html
+        reportgenerator -reports:WebApiServer/coverage.cobertura.xml -targetdir:WebApiServer/coverage-report -reporttypes:Html
 
     - name: Annotate Cobertura Test Logs
       run: |
-        if [ -f "./coverage/coverage.cobertura.xml" ]; then
-          warnings=$(grep -i "warning" ./coverage/coverage.cobertura.xml)
-          errors=$(grep -i "error" ./coverage/coverage.cobertura.xml)
+        if [ -f "WebApiServer/coverage.cobertura.xml" ]; then
+          warnings=$(grep -i "warning" WebApiServer/coverage.cobertura.xml)
+          errors=$(grep -i "error" WebApiServer/coverage.cobertura.xml)
           if [ -n "$warnings" ]; then
             echo "$warnings" | while read -r line; do
               echo "::warning::Cobertura warning: $line"
@@ -126,8 +136,7 @@ jobs:
               echo "::error::Cobertura error: $line"
             done
           fi
-        fi
-        
+        fi        
 #        - name: Test the project and capture logs
 #          run: dotnet test -c Release --verbosity normal WebApiServer/WebApiServer.csproj > test.log 2>&1
     
