Update ci.yml

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -26,19 +26,44 @@ jobs:
       with:
         dotnet-version: '8.0.x' # Update to the latest version that supports .NET 8.0
 
-    - name: Build the project and capture logs
-      run: dotnet build --no-incremental -warnaserror > build.log 2>&1 || true
+    - name: Install dependencies for React
+      run: npm install
+      working-directory: ./clientapp
 
-    - name: Annotate Build Logs
+    - name: Build npm package and capture logs
+      id: npm-build
+      run: |
+        echo "Starting npm build..."
+        npm run build > npm_build.log 2>&1 || true
+      working-directory: ./clientapp
+      continue-on-error: true
+
+    - name: Annotate npm Build Logs
+      run: |
+        # npm build warnings
+        grep -i "warning" clientapp/npm_build.log | while read -r line; do
+          echo "::warning file=${{ github.workspace }}/clientapp/npm_build.log::$line"
+        done || true
+
+        # npm build errors
+        grep -i "error" clientapp/npm_build.log | while read -r line; do
+          echo "::error file=${{ github.workspace }}/clientapp/npm_build.log::$line"
+        done || true
+
+    - name: Build .NET and React app
+      id: dotnet-build
+      run: dotnet build --no-incremental -warnaserror > dotnet_build.log 2>&1 || true
+
+    - name: Annotate .NET Build Logs
       run: |
         # .NET build warnings
-        grep "warning" build.log | while read -r line; do
-          echo "::warning file=${{ github.workspace }}/build.log::$line"
+        grep "warning" dotnet_build.log | while read -r line; do
+          echo "::warning file=${{ github.workspace }}/dotnet_build.log::$line"
         done || true
 
         # .NET build errors
-        grep "error" build.log | while read -r line; do
-          echo "::error file=${{ github.workspace }}/build.log::$line"
+        grep "error" dotnet_build.log | while read -r line; do
+          echo "::error file=${{ github.workspace }}/dotnet_build.log::$line"
         done || true
 
     - name: Test the project and capture logs
