Update ci.yml

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -41,33 +41,17 @@ jobs:
         done || true
 
   
-    - name: Install dependencies for React
-      run: npm install
-      working-directory: ./clientapp
+#    - name: Install dependencies for React
+#      run: npm install
+#      working-directory: ./clientapp
 
-    - name: Build npm package and capture logs
-      id: npm-build
-      run: |
-        echo "Starting npm build..."
-        npm run build > npm_build.log 2>&1 || true
-      working-directory: ./clientapp
-      continue-on-error: true
-
-    - name: Find npm_build.log
-      run: |
-        echo "Looking for npm_build.log..."
-        find . -name npm_build.log -exec echo "Found: {}" \;
-        
-    - name: Annotate npm Build Logs
-      run: |
-        # npm build warnings
-        grep -i "warning" clientapp/npm_build.log | while read -r line; do
-          echo "::warning file=${{ github.workspace }}/clientapp/npm_build.log::$line"
-        done || true
-        # npm build errors
-        grep -i "error" clientapp/npm_build.log | while read -r line; do
-          echo "::error file=${{ github.workspace }}/clientapp/npm_build.log::$line"
-        done || true
+#    - name: Build npm package and capture logs
+#      id: npm-build
+#      run: |
+#        echo "Starting npm build..."
+#        npm run build > npm_build.log 2>&1 || true
+#      working-directory: ./clientapp
+#      continue-on-error: true
 
     - name: Test the project and capture logs
       run: dotnet test -c Release --verbosity normal WebApiServer/WebApiServer.csproj > test.log 2>&1 || true
@@ -94,4 +78,19 @@ jobs:
         grep "error" publish.log | while read -r line; do
           echo "::error::$line"
         done || true
-
+        
+    - name: Find npm_build.log
+      run: |
+        echo "Looking for npm_build.log..."
+        find . -name npm_build.log -exec echo "Found: {}" \;
+        
+    - name: Annotate npm Build Logs
+      run: |
+        # npm build warnings
+        grep -i "warning" clientapp/npm_build.log | while read -r line; do
+          echo "::warning file=${{ github.workspace }}/clientapp/npm_build.log::$line"
+        done || true
+        # npm build errors
+        grep -i "error" clientapp/npm_build.log | while read -r line; do
+          echo "::error file=${{ github.workspace }}/clientapp/npm_build.log::$line"
+        done || true
