Update ci.yml

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -50,14 +50,18 @@ jobs:
         cd clientapp
         npm run lint > npm_lint.log 2>&1 || true
 
-    - name: Annotate npm lint warnings
+    - name: Annotate npm lint warnings and errors
       run: |
-        grep -i 'warning' clientapp/npm_lint.log | while read -r line; do echo "::warning title=NPM Lint::$line"; done
+        # Annotate warnings from npm lint
+        grep -i 'warning' clientapp/npm_lint.log | while read -r line; do
+          echo "::warning title=NPM Lint::$line"
+        done || true
 
-    - name: Annotate npm lint errors
-      run: |
-         grep -i 'error' clientapp/npm_lint.log | while read -r line; do echo "::error title=NPM Lint::$line"; done
-
+        # Annotate errors from npm lint
+        grep -i 'error' clientapp/npm_lint.log | while read -r line; do
+          echo "::error title=NPM Lint::$line"
+        done || true
+        
     - name: Display npm lint logs
       run: |
         echo "==== NPM LINT LOG ===="
@@ -74,7 +78,7 @@ jobs:
     - name: Test the project and capture logs
       run: dotnet test -c Release --verbosity normal WebApiServer/WebApiServer.csproj > test.log 2>&1 || true
 
-    - name: .NET Test log
+    - name: Annotate .NET Test log
       run: |
         grep "warning" test.log | while read -r line; do
           echo "::warning title=.NET Test::$line"
@@ -87,7 +91,7 @@ jobs:
     - name: Publish the project and capture logs
       run: dotnet publish WebApiServer/WebApiServer.csproj -c Release -o ./dotnet_publish -p:Version="${{ github.sha }}" > publish.log 2>&1 || true
 
-    - name: .NET Publish log
+    - name: Annotate .NET Publish log
       run: |
         grep "warning" publish.log | while read -r line; do
           echo "::warning::$line"
@@ -98,7 +102,7 @@ jobs:
         done || true
 
         
-    - name: npm run log
+    - name: Annotate npm run log
       run: |
         # npm build warnings
         grep -i "warning" clientapp/npm_build.log | while read -r line; do
