Update ci.yml

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -38,6 +38,7 @@ jobs:
         grep "error" ./webapi_build.log | while read -r line; do
           echo "::error title=.NET Lint::$line"
         done || true
+
     - name: Install dependencies for React
       run: npm install
       working-directory: ./clientapp
@@ -46,6 +47,7 @@ jobs:
       run: |
         cd clientapp
         npm run lint > npm_lint.log 2>&1 || true
+
     - name: Annotate npm lint warnings and errors
       run: |
         # Annotate warnings from npm lint
@@ -70,17 +72,24 @@ jobs:
       working-directory: ./clientapp
       continue-on-error: true
 
-    - name: Test the project and capture logs
-      run: dotnet test -c Release --verbosity normal WebApiServer/WebApiServer.csproj > test.log 2>&1 || true
+#    - name: Test the project and capture logs
+#      run: dotnet test -c Release --verbosity normal WebApiServer/WebApiServer.csproj > test.log 2>&1 || true
 
-    - name: Annotate .NET Test log
-      run: |
-        grep "warning" test.log | while read -r line; do
-          echo "::warning title=.NET Test::$line"
-        done || true
-        grep "error" test.log | while read -r line; do
-          echo "::error title=.NET Test::$line"
-        done || true
+#    - name: Annotate .NET Test log
+#      run: |
+#        grep "warning" test.log | while read -r line; do
+#          echo "::warning title=.NET Test::$line"
+#        done || true
+#        grep "error" test.log | while read -r line; do
+#          echo "::error title=.NET Test::$line"
+#        done || true
+
+    - name: Run Test and Annotate Action
+      uses: ./.github/actions/test-and-annotate
+      with:
+        test-dir: 'WebApiServer'
+        test-library: 'WebApiServer'
+
     - name: Publish the project and capture logs
       run: dotnet publish WebApiServer/WebApiServer.csproj -c Release -o ./dotnet_publish -p:Version="${{ github.sha }}" > publish.log 2>&1 || true
 
@@ -89,7 +98,6 @@ jobs:
         grep "warning" publish.log | while read -r line; do
           echo "::warning::$line"
         done
-    
         grep "error" publish.log | while read -r line; do
           echo "::error::$line"
         done || true
